[workspace]
members = [
    "drivers/net/phy/ax88796b",
    "r4l/",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Weikang Guo <guoweikang.kernel@gmail.com>"]
edition = "2021"

[profile.dev]
lto = false
debug = true

[profile.release]
lto = true

